### PR TITLE
MNT: Re-rendered with conda-smithy 2.0.1

### PR DESCRIPTION
**Pull request by pmlandwehr**

### CODE REVIEW

**Comment by pmlandwehr** [comment]
Depending on `python-editor` not having a `py36` version. Should be re-renderable once https://github.com/conda-forge/python-editor-feedstock/pull/3 finishes and is merged.

**Comment by pmlandwehr** [comment]
Now crashing out because of a missing build of `rsa` for `py36`

**Comment by pmlandwehr** [comment]
According to pypi, `1.11.44` should support `py36`, solving the problem.

**Comment by pmlandwehr** [comment]
Well, now I feel like giving up.

**Comment by jakirkham** [comment]
It's a dependency issue. Presumably `botocore` needs re-rendering. Though as `awscli` pins the version of `botocore`, you will need that version exactly. Maybe worth double checking if the new version of `awscli` has updated dependencies.

**Comment by hajapy** [comment]
According to https://github.com/aws/aws-cli/blob/1.11.44/setup.py, we should be ok with botocore 1.5.7, which is currently re-rendering: https://github.com/conda-forge/botocore-feedstock/pull/7

**Pull request merged**
